name: "aihub_en-ko_bpe"
joeynmt_version: "2.0.0"

data:
    train: "../../data/aihub_en-ko/processed/data/spaced/compat_f/train"
    dev: "../../data/aihub_en-ko/processed/data/spaced/compat_f/dev"
    test: "../../data/aihub_en-ko/processed/data/spaced/compat_f/test"
    dataset_type: "plain"
    vocab_type: "compat" # "compat", "positional", "syllable"
    sample_dev_subset: 5000 # run validation on this number of random samples from dev set, fixed seed 42 in datasets.py
    src:
        lang: "en"
        max_length: 100
        lowercase: True
        normalize: False
        level: "bpe"
        voc_min_freq: 1
        voc_file: "../../data/aihub_en-ko/processed/data/spaced/compat_f/bpe_en_6000.txt"
        tokenizer_type: "huggingface_bpe"
        tokenizer_cfg:
            num_merges: 6000
            #codes: "../../data/aihub_en-ko/processed/data/spaced/compat/hf_bpe_en.10000"
            model_file: "../../data/aihub_en-ko/processed/data/spaced/compat_f/bpe_en.6000"
            pretokenizer: "moses"
    trg:
        lang: "ko"
        max_length: 100
        lowercase: True
        normalize: False
        level: "bpe"
        voc_min_freq: 1
        voc_file: "models/compat_f_6551/trg_vocab.txt"
        # mask_file: "models/compat_f_6551/vocab_ko_6551_mask.pt" # comment for no masking
        # tag_file: "models/compat_f_6551/vocab_ko_6551_tag.pt" # comment for no masking
        tokenizer_type: "huggingface_bpe"
        tokenizer_cfg:
            num_merges: 6551
            #codes: "../../data/aihub_en-ko/processed/data/spaced/compat/hf_bpe_ko.6000"
            model_file: "models/compat_f_6551/bpe_ko.6551"
            pretokenizer: "none"

testing:
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 1024
    batch_type: "token"
    max_output_length: 100
    eval_metrics: [] # ["bleu", "chrf"]
    return_prob: "ref" # "none" to enable beamsearch, "ref" then no search needed
    return_attention: False
    sacrebleu_cfg:
        tokenize: "none"
        lowercase: True
    masked: False # masked inference, set False during training, True during inference with beam search

training:
    # load_model: "models/non-compat_hf_bpe_10000_ppl_masked_1.5_fixed/best.ckpt"
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.98]
    scheduling: "warmupinversesquareroot"
    learning_rate_warmup: 4000
    patience: 5
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0005
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    batch_multiplier: 1
    early_stopping_metric: "ppl" 
    validation_step_patience: 5 # default is 5
    epochs: 100
    validation_freq: -1 # set -1 for validation every epoch
    logging_freq: 1000
    model_dir: "models/compat_f_test_big_6551_en6k"
    overwrite: False
    shuffle: True
    use_cuda: True
    cuda_device: 3
    print_valid_sents: [0, 1, 2, 3, 4]
    keep_best_ckpts: 1
    theta: 1.5 # penalty for invalid tokens during softmax (1.0 = no penalty)
    add_loss_term: False

model:
    initializer: "xavier_uniform"
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: False
    tied_softmax: False
    use_compile: False # set to True to use model = torch.compile(model)
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 1024
        dropout: 0.1
        layer_norm: "pre"
        activation: "relu"
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 1024
        dropout: 0.1
        layer_norm: "pre"
        activation: "relu"
