name: "aihub_en-ko_bpe"
joeynmt_version: "2.0.0"

data:
    train: "../../data/aihub_en-ko/processed/data/spaced/syllable/train"
    dev: "../../data/aihub_en-ko/processed/data/spaced/syllable/dev"
    test: "../../data/aihub_en-ko/processed/data/spaced/syllable/test"
    dataset_type: "plain"
    sample_dev_subset: 5000 # run validation on this number of random samples from dev set, fixed seed 42 in datasets.py
    src:
        lang: "en"
        max_length: 100
        lowercase: True
        normalize: False
        level: "bpe"
        voc_min_freq: 1
        voc_file: "../../data/aihub_en-ko/processed/data/spaced/syllable/hf_bpe_vocab_en_20000.txt"
        tokenizer_type: "huggingface_bpe"
        tokenizer_cfg:
            num_merges: 20000
            #codes: "../../data/aihub_en-ko/processed/data/spaced/compat/hf_bpe_en.10000"
            model_file: "../../data/aihub_en-ko/processed/data/spaced/syllable/hf_bpe_en.20000"
            pretokenizer: "moses"
    trg:
        lang: "ko"
        max_length: 100
        lowercase: True
        normalize: False
        level: "bpe"
        voc_min_freq: 1
        voc_file: "../../data/aihub_en-ko/processed/data/spaced/syllable/hf_bpe_vocab_ko_20000.txt"
        mask_file: "../../data/aihub_en-ko/processed/data/spaced/syllable/hf_bpe_vocab_ko_20000.pt"
        tokenizer_type: "huggingface_bpe"
        tokenizer_cfg:
            num_merges: 20000
            #codes: "../../data/aihub_en-ko/processed/data/spaced/compat/hf_bpe_ko.6000"
            model_file: "../../data/aihub_en-ko/processed/data/spaced/syllable/hf_bpe_ko.20000"
            pretokenizer: "none"

testing:
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 1024
    batch_type: "token"
    max_output_length: 100
    eval_metrics: [] # ["bleu", "chrf"]
    return_prob: "ref" # "none" to enable beamsearch, "ref" then no search needed
    return_attention: False
    sacrebleu_cfg:
        tokenize: "none"
        lowercase: True

training:
    #load_model: "models/transformer_iwslt14_deen_bpe/best.ckpt"
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.98]
    scheduling: "warmupinversesquareroot"
    learning_rate_warmup: 4000
    patience: 5
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0005
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    early_stopping_metric: "ppl" 
    validation_step_patience: 5 # default is 5
    epochs: 100
    validation_freq: 10000
    logging_freq: 1000
    model_dir: "models/syllable_hf_bpe_20000_20000_ppl"
    overwrite: False
    shuffle: True
    use_cuda: True
    cuda_device: 7
    print_valid_sents: [0, 1, 2, 3, 4]
    keep_best_ckpts: 1

model:
    initializer: "xavier_uniform"
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: False
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 256
        ff_size: 1024
        dropout: 0.3
        layer_norm: "pre"
        activation: "relu"
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 256
        ff_size: 1024
        dropout: 0.3
        layer_norm: "pre"
        activation: "relu"
